---
schema_version: 2
committing:
  automated:
    - cargo fmt --all -- --check
    - cargo build
    - cargo clippy
    - cargo test
    - yamllint -s .checklist.yml .travis.yml
  manual:
    - checked that the version number has been bumped
    - checked that the schema version number has been bumped
