[package]
name = "checklist"
version = "0.1.1"
authors = ["Mike Stipicevic <stipredirect@gmail.com>"]
edition = "2018"

[dependencies]
console = "0.7.5"
dialoguer = "0.3.0"
failure = "0.1.5"
maplit = "1.0.1"
serde = "1.0.88"
serde_derive = "1.0.88"
serde_yaml = "0.8.8"
structopt = "0.2.14"

[dev-dependencies]
assert_fs = "0.11.3"
scopeguard = "1.0.0"
