[package]
name = "checklist"
version = "0.1.0"
authors = ["Mike Stipicevic <stipredirect@gmail.com>"]
edition = "2018"

[dependencies]
dialoguer = "0.3.0"
maplit = "1.0.1"
serde = "1.0.88"
serde_derive = "1.0.88"
serde_yaml = "0.8.8"
structopt = "0.2.14"
tempfile = "3.0.7"
